// Section anchors shared by the header nav and the route rail. Order = page order.
const SITE_STOPS=[{id:'top',nav:'home',key:'nav.home',label:'Home'},{id:'about',nav:'about',key:'nav.about',label:'About'},{id:'work',nav:'work',key:'nav.work',label:'What I do'},{id:'journey',nav:'journey',key:'nav.journey',label:'Journey'},{id:'products',nav:'products',key:'nav.products',label:'Products'},{id:'contact',nav:'contact',key:'nav.contact',label:'Book an Appointment'}];
class AppHeader extends HTMLElement {
  connectedCallback(){const page=this.getAttribute('active')||'home';const links=SITE_STOPS.filter(s=>s.id!=='top').map(s=>`<a data-nav="${s.nav}" data-scroll="${s.id}" href="index.html#${s.id}" data-i18n="${s.key}">${s.label}</a>`).join('');this.innerHTML=`<header class="site-header"><div class="container nav-wrap"><a class="logo" data-nav="home" data-scroll="top" href="index.html#top">Rami Alkhateeb</a><div class="nav-controls"><button class="language-toggle" type="button" aria-label="Switch language">العربية</button><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div><nav class="nav-links" aria-label="Main navigation">${links}</nav></div></header>`;const active=this.querySelector(`[data-nav="${page}"]`);if(active)active.classList.add('active');const nav=this.querySelector('.nav-links');const toggle=this.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(nav.classList.contains('open')))});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}});}
}
customElements.define('app-header',AppHeader);
// The route rail: one dot per section, echoing the journey map's drawn route.
// Only present on the single page (index.html) — product.html omits it.
class AppRail extends HTMLElement {
  connectedCallback(){const dots=SITE_STOPS.map(s=>`<a class="rail-dot" data-scroll="${s.id}" href="#${s.id}"><span class="rail-mark"></span><span class="rail-label" data-i18n="${s.key}">${s.label}</span></a>`).join('');this.innerHTML=`<nav class="route-rail" aria-label="Section navigation"><span class="rail-line"><span class="rail-progress"></span></span>${dots}</nav>`;}
}
customElements.define('app-rail',AppRail);
class AppFooter extends HTMLElement {connectedCallback(){this.innerHTML=`<footer class="site-footer"><div class="container"><p class="footer-brand">Rami Alkhateeb</p><div class="footer-links"><a href="https://linkedin.com/in/rami13alkhateeb" target="_blank" rel="noopener">LinkedIn</a><a href="https://github.com/ramialkhateeb" target="_blank" rel="noopener">GitHub</a><a href="guides.html" data-i18n="nav.guides">Guides</a><a href="https://rami13kh.substack.com/" target="_blank" rel="noopener">Blog</a></div><p data-i18n="footer.copy">© 2026 Rami Alkhateeb.</p><small><a href="impressum.html">Impressum</a> · <a href="privacy.html">Privacy</a></small></div></footer>`;}}
customElements.define('app-footer',AppFooter);
