// Section anchors shared by the header nav and the route rail. Order = page order.
const SITE_STOPS=[{id:'top',nav:'home',key:'nav.home',label:'Home'},{id:'about',nav:'about',key:'nav.about',label:'About'},{id:'work',nav:'work',key:'nav.work',label:'What I do'},{id:'products',nav:'products',key:'nav.products',label:'Products'},{id:'contact',nav:'contact',key:'nav.contact',label:'Book an Appointment'}];
class AppHeader extends HTMLElement {
  connectedCallback(){const page=this.getAttribute('active')||'home';const links=SITE_STOPS.filter(s=>s.id!=='top').map(s=>`<a data-nav="${s.nav}" data-scroll="${s.id}" href="index.html#${s.id}" data-i18n="${s.key}">${s.label}</a>`).join('');this.innerHTML=`<header class="site-header"><div class="container nav-wrap"><a class="logo" data-nav="home" data-scroll="top" href="index.html#top">Rami Alkhateeb</a><div class="nav-controls"><button class="language-toggle" type="button" aria-label="Switch language">العربية</button><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div><nav class="nav-links" aria-label="Main navigation">${links}</nav></div></header>`;const active=this.querySelector(`[data-nav="${page}"]`);if(active)active.classList.add('active');const nav=this.querySelector('.nav-links');const toggle=this.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(nav.classList.contains('open')))});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}});}
}
customElements.define('app-header',AppHeader);
// The route rail: one dot per section, echoing the journey map's drawn route.
// Only present on the single page (index.html) — product.html omits it.
class AppRail extends HTMLElement {
  connectedCallback(){const dots=SITE_STOPS.map(s=>`<a class="rail-dot" data-scroll="${s.id}" href="#${s.id}"><span class="rail-mark"></span><span class="rail-label" data-i18n="${s.key}">${s.label}</span></a>`).join('');this.innerHTML=`<nav class="route-rail" aria-label="Section navigation"><span class="rail-line"><span class="rail-progress"></span></span>${dots}</nav>`;}
}
customElements.define('app-rail',AppRail);
// Decorative sea layer (light rays, drifting particles, 3D-rendered canoe sprite). Water colour itself is painted on
// <body> by initSea() in site.js; this layer sits between that and the page content.
const SEA_BITS=[[6,22,0],[14,28,-9],[23,19,-4],[31,31,-15],[42,24,-7],[51,34,-20],[60,21,-2],[68,27,-12],[77,33,-6],[85,23,-17],[92,29,-10],[97,25,-3]];
const CANOE_SVG=`<svg class="sea-canoe-art" viewBox="0 0 360 118" aria-hidden="true"><defs><filter id="pGrain" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency=".9" numOctaves="2" seed="4"/><feColorMatrix values="0 0 0 0 .4 0 0 0 0 .4 0 0 0 0 .4 0 0 0 .5 -.16"/></filter><filter id="pBlur" x="-20%" y="-80%" width="140%" height="260%"><feGaussianBlur stdDeviation="6 2"/></filter><linearGradient id="pFace" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#e6e6e6"/></linearGradient><linearGradient id="pWater" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#dcecf0" stop-opacity=".55"/><stop offset="1" stop-color="#5f8a99" stop-opacity="0"/></linearGradient><linearGradient id="pFade" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#000"/><stop offset=".14" stop-color="#fff"/><stop offset=".86" stop-color="#fff"/><stop offset="1" stop-color="#000"/></linearGradient><mask id="pWm" maskUnits="userSpaceOnUse" x="0" y="80" width="360" height="38"><rect x="0" y="80" width="360" height="38" fill="url(#pFade)"/></mask><clipPath id="pClip"><path d="M14 58 H112 L180 6 L248 58 H346 L306 100 H54Z"/></clipPath></defs><ellipse cx="180" cy="100" rx="150" ry="6" fill="#06141c" opacity=".35" filter="url(#pBlur)"/><path d="M14 58 L6 42 L62 58Z" fill="#dcdcdc"/><path d="M346 58 L354 42 L298 58Z" fill="#e3e3e3"/><path d="M14 58 H346 L306 100 H54Z" fill="url(#pFace)"/><path d="M112 58 L180 6 V58Z" fill="#fff"/><path d="M180 6 L248 58 H180Z" fill="#e2e2e2"/><g clip-path="url(#pClip)"><rect width="360" height="118" filter="url(#pGrain)" opacity=".5"/></g><path d="M112 58 L54 100 M248 58 L306 100 M14 58 L54 100 M346 58 L306 100 M30 79 H330" stroke="#b5b5b5" stroke-opacity=".4" stroke-width=".8" fill="none"/><path d="M112 58 L180 6 L248 58 M180 6 V58" stroke="#c4c4c4" stroke-width=".9" stroke-linejoin="round" fill="none"/><path d="M6 42 L14 58 H112 M248 58 H346 L354 42" stroke="#fff" stroke-width="1.6" stroke-linejoin="round" stroke-linecap="round" fill="none"/><path d="M54 100 H306" stroke="#000" stroke-opacity=".16" stroke-width="1.2"/><g mask="url(#pWm)"><rect x="0" y="94" width="360" height="24" fill="url(#pWater)"/><path d="M0 94 Q45 90 90 94 T180 94 T270 94 T360 94" fill="none" stroke="#fff" stroke-opacity=".7" stroke-width="1.4"/><ellipse class="canoe-ripple" cx="180" cy="96" rx="170" ry="7"/><ellipse class="canoe-ripple r2" cx="180" cy="96" rx="170" ry="7"/></g></svg>`;
class AppSea extends HTMLElement {
  connectedCallback(){document.body.classList.add('sea-page');const rays=[0,1,2,3].map(i=>`<span class="sea-ray sea-ray-${i}"></span>`).join('');const bits=SEA_BITS.map(([x,d,delay])=>`<span class="sea-bit" style="--x:${x}%;--dur:${d}s;--delay:${delay}s"></span>`).join('');this.innerHTML=`<div class="sea-photo" aria-hidden="true"></div><div class="sea-fx" aria-hidden="true">${rays}${bits}<div class="sea-canoe"><div class="sea-canoe-face">${CANOE_SVG}</div></div></div>`;}
}
customElements.define('app-sea',AppSea);
class AppFooter extends HTMLElement {connectedCallback(){this.innerHTML=`<footer class="site-footer"><div class="container"><p class="footer-brand">Rami Alkhateeb</p><div class="footer-links"><a href="https://linkedin.com/in/rami13alkhateeb" target="_blank" rel="noopener">LinkedIn</a><a href="https://github.com/ramialkhateeb" target="_blank" rel="noopener">GitHub</a><a href="guides.html" data-i18n="nav.guides">Guides</a><a href="https://rami13kh.substack.com/" target="_blank" rel="noopener">Blog</a></div><p data-i18n="footer.copy">© 2026 Rami Alkhateeb.</p><small><a href="impressum.html">Impressum</a> · <a href="privacy.html">Privacy</a></small></div></footer>`;}}
customElements.define('app-footer',AppFooter);
