// x/y below are % position (0-100) on assets/images/Europe-middle-east.png (1050x760px),
// used to place the About page's journey-map marker for that country.
// To move a marker: open the image at full size, find the country's pixel position (px,py),
// then set x = px/1050*100 and y = py/760*100. Same country must always use the same x/y.
// Current values are an eyeballed approximation — nudge freely.
window.RAMI_JOURNEY=[
{country:'Germany',flag:'🇩🇪',x:26,y:15,company:'HILTES Software GmbH',role:'Software Engineer',location:'Germany',period:'Apr 2026 – Present',bullets:['Designed and built ~30 reusable UI components from scratch, replacing DevExpress ASP.NET/Blazor components and removing commercial UI licenses across a 5-developer team.','Contributed to the architecture and business logic of MasterDataService, the core service of a microservices-based platform.','Built a CI quality/security pipeline that catches unwanted AI-generated BOMs and artifacts before merging.']},
{country:'UAE',flag:'🇦🇪',x:85,y:69,company:'CARMA',role:'Software Engineer',location:'Dubai, UAE',period:'Dec 2022 – Apr 2025',bullets:['Modernized legacy justice systems and migrated 5+ enterprise services from VB.NET to modern .NET architectures.','Designed secure integration layers with Dubai Police for automated forensic-evidence processing.','Improved engineering quality through unit testing, SOLID principles, and maintainable service design.']},
{country:'UAE',flag:'🇦🇪',x:85,y:69,company:'Tech Unicorn',role:'Software Engineer',location:'Dubai, UAE',period:'Sep 2021 – Dec 2022',bullets:['Provided technical leadership for two developers, including sprint coordination, mentoring, and code-quality guidance.','Designed services in a .NET microservices environment using Azure Functions and Service Bus.','Contributed to migrating enterprise projects to Microsoft Azure and building CI/CD pipelines.']},
{country:'Syria',flag:'🇸🇾',x:61,y:49,company:'Syriatel Mobile Telecom',role:'Full Stack Developer',location:'Damascus, Syria',period:'Oct 2018 – Feb 2020',bullets:['Designed and developed internal enterprise applications for a telecom environment serving 10M+ customers.','Built a configuration-driven module for Customer Action Tracking that reduced repeated page-specific development.','Delivered modules for KYC and prize-management systems using .NET and Angular.']}
];
