const TEXT={en:{'nav.home':'Home','nav.projects':'Projects','nav.guides':'Guides','nav.posts':'Posts','nav.about':'About','nav.book':'Book a call','footer.copy':'© 2026 Rami Alkhateeb.','home.eyebrow':'Software Engineer','home.title':'I build useful digital products.','home.intro':'A selection of web and mobile projects.','home.view':'View projects','home.work':'Selected projects','project.view':'View project','project.source':'Source on GitHub','project.download':'Download APK','project.browse':'Browse web app','project.notFound':'Project not found','project.notFoundText':'This project does not exist or its link is incomplete.','media.logo':'App logo','media.wide':'Wide project image','media.screen':'Phone screenshot'},ar:{'nav.home':'الرئيسية','nav.projects':'المشاريع','nav.guides':'الأدلة','nav.posts':'المقالات','nav.about':'من نحن','nav.book':'احجز موعداً','footer.copy':'© 2026 رامي الخطيب.','home.eyebrow':'مهندس برمجيات','home.title':'أبني منتجات رقمية مفيدة.','home.intro':'مجموعة مختارة من مشاريع الويب والهاتف.','home.view':'استعرض المشاريع','home.work':'مشاريع مختارة','project.view':'عرض المشروع','project.source':'المصدر على GitHub','project.download':'تحميل APK','project.browse':'تصفح التطبيق','project.notFound':'المشروع غير موجود','project.notFoundText':'هذا المشروع غير موجود أو أن رابطه غير مكتمل.','media.logo':'شعار التطبيق','media.wide':'صورة المشروع العريضة','media.screen':'لقطة شاشة للهاتف'}};
let language=localStorage.getItem('rami-language')||'en';
const t=key=>TEXT[language][key]||key;
const esc=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function image(path,alt,kind){return `<div class="media-placeholder ${kind}"><img src="${esc(path)}" alt="${esc(alt)}" onerror="this.remove();this.parentElement.classList.add('missing')"><span>${esc(alt)}</span></div>`}
function renderProjects(){const grid=document.getElementById('project-grid');if(!grid)return;grid.innerHTML=RAMI_PROJECTS.map(p=>{const c=p[language];return `<article class="project-card"><div class="project-logo">${image(p.logo,t('media.logo'),'logo-media')}</div><div class="project-body"><h3>${esc(c.title)}</h3><p>${esc(c.short)}</p><a class="text-link" href="project.html?project=${encodeURIComponent(p.slug)}">${t('project.view')} <i class="fa-solid fa-arrow-right"></i></a></div></article>`}).join('')}
function renderProjectDetail(){const target=document.getElementById('project-detail');if(!target)return;const slug=new URLSearchParams(location.search).get('project'),p=RAMI_PROJECTS.find(item=>item.slug===slug);if(!p){target.innerHTML=`<div class="empty-state"><h1>${t('project.notFound')}</h1><p>${t('project.notFoundText')}</p><a class="btn" href="index.html#projects">${t('nav.projects')}</a></div>`;return}const c=p[language];const media=p.layout==='wide'?`<div class="wide-media">${image(p.wideImage,t('media.wide'),'wide-image')}</div>`:`<div class="phone-gallery">${p.screenshots.map((src,i)=>image(src,`${t('media.screen')} ${i+1}`,'phone-image')).join('')}</div>`;const actions=[p.apkUrl&&`<a class="btn" href="${esc(p.apkUrl)}" target="_blank" rel="noopener">${t('project.download')}</a>`,p.webUrl&&`<a class="btn btn-outline" href="${esc(p.webUrl)}" target="_blank" rel="noopener">${t('project.browse')}</a>`,p.sourceUrl&&`<a class="btn btn-outline" href="${esc(p.sourceUrl)}" target="_blank" rel="noopener"><i class="fa-brands fa-github"></i>${t('project.source')}</a>`].filter(Boolean).join('');target.innerHTML=`<h1>${esc(c.title)}</h1><p class="description">${esc(c.description)}</p>${media}${actions?`<div class="project-actions">${actions}</div>`:''}`}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));document.querySelectorAll('.language-toggle').forEach(el=>el.textContent=language==='en'?'العربية':'English');renderProjects();renderProjectDetail()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.booking-link').forEach(a=>a.href=window.PORTFOLIO_CONFIG?.calendlyUrl||'#');document.addEventListener('click',e=>{if(e.target.closest('.language-toggle')){language=language==='en'?'ar':'en';localStorage.setItem('rami-language',language);applyLanguage()}});applyLanguage()});
